apiVersion: apps/v1
kind: Deployment        # тип ресурса деплоймент
metadata:
  name: {{ .Values.app.name }}
  labels:               # лейблы которые нужны для стыковки с сервисом
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}  # количество реплик пода
  selector:
    matchLabels:        # определяет с какими лейблами стыковаться
      {{- include "app.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate # выбор стратегии выкатки пода: создаёт новый под и не переключает трафик, пока новый под не получит статус ready
  template:             # описание шаблона для создания подов
    metadata:
      name: {{ .Values.app.name }}-pod
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
      annotations:  # это метаданные с дополнительной информацией, связанной с ресурсом или объектом. Аннотации состоят из пар ключ-значение. Каждая пара используется для описания метаданных ресурса или предоставления дополнительной информации
        rollme: {{ randAlphaNum 5 | quote }}
        branch: "{{ .Values.app.branch }}"
    spec:
      affinity:       # для отказоустойчивости запретим двум подам запускаться на одной ноде
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: helm.sh/chart  # указываем ключ лейбла
                operator: In
                values:
                - {{ .Values.app.name }}       # указываем значение - имя чарта
            topologyKey: "kubernetes.io/hostname"
      containers:                   # характеристики создаваемого пода
      - env:
        {{- include "hello-app.EnvStartup" . | indent 8 }} 
        image: "{{ .Values.image.app }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: {{ .Values.app.name }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        resources:
          limits:                   # максимум ресурсов, выделяемых контейнеру
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
          requests:                 #минимальное количество ресурсов необходимых для создания пода
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 15
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 15
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - name: app-temp
          mountPath: /tmp
      volumes:
      - name: app-temp
        emptyDir: {}